LOCAL sysLib IS import("system").
LOCK STEERING TO RETROGRADE.
WAIT 10.
LOCK THROTTLE TO 1.
WAIT UNTIL ALT:PERIAPSIS < 15000.
LOCK THROTTLE TO 0.
LOCK STEERING TO SRFRETROGRADE.
WAIT UNTIL ALT:RADAR < 15000.
UNTIL STAGE:NUMBER=0 sysLib["AutoStage"]().
WAIT UNTIL ALT:RADAR < 700.
UNLOCK STEERING.